-- ====================================================================
-- SUPABASE POSTGRESQL MIGRATION SCRIPT FOR TABLE: video_download_jobs
-- Run this script directly in Supabase Dashboard -> SQL Editor
-- ====================================================================

-- 1. Tạo bảng video_download_jobs
CREATE TABLE IF NOT EXISTS public.video_download_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NULL,
    source_url TEXT NOT NULL,
    platform VARCHAR(30),
    title VARCHAR(500),
    author VARCHAR(255),
    thumbnail_url TEXT,
    requested_format VARCHAR(20) NOT NULL DEFAULT 'mp4',
    requested_quality VARCHAR(30),
    format_id VARCHAR(100),
    file_path TEXT,
    file_name VARCHAR(500),
    file_size BIGINT,
    duration INTEGER,
    progress SMALLINT NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    error_message TEXT,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT video_download_jobs_progress_check
        CHECK (progress >= 0 AND progress <= 100),

    CONSTRAINT video_download_jobs_status_check
        CHECK (
            status IN (
                'pending',
                'inspecting',
                'ready',
                'processing',
                'completed',
                'failed',
                'expired'
            )
        ),

    CONSTRAINT video_download_jobs_format_check
        CHECK (requested_format IN ('mp4', 'mp3'))
);

-- 2. Tạo Indexes cho hiệu năng truy vấn PostgreSQL
CREATE INDEX IF NOT EXISTS video_download_jobs_user_id_index
ON public.video_download_jobs(user_id);

CREATE INDEX IF NOT EXISTS video_download_jobs_status_index
ON public.video_download_jobs(status);

CREATE INDEX IF NOT EXISTS video_download_jobs_expires_at_index
ON public.video_download_jobs(expires_at);

CREATE INDEX IF NOT EXISTS video_download_jobs_user_status_index
ON public.video_download_jobs(user_id, status);

-- 3. Tạo Trigger tự động cập nhật updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_video_download_jobs_updated_at
ON public.video_download_jobs;

CREATE TRIGGER set_video_download_jobs_updated_at
BEFORE UPDATE ON public.video_download_jobs
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- 4. Bật Supabase Row Level Security (RLS)
ALTER TABLE public.video_download_jobs ENABLE ROW LEVEL SECURITY;

-- Policy 1: Người dùng xem các tác vụ của chính mình
CREATE POLICY "Users can view their own video jobs"
ON public.video_download_jobs
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- Policy 2: Người dùng khởi tạo tác vụ của chính mình
CREATE POLICY "Users can create their own video jobs"
ON public.video_download_jobs
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Policy 3: Người dùng xóa tác vụ của chính mình
CREATE POLICY "Users can delete their own video jobs"
ON public.video_download_jobs
FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- 5. Liên kết khóa ngoại nếu sử dụng Supabase Auth (auth.users)
-- Bỏ comment dòng dưới nếu ứng dụng kết nối trực tiếp với Supabase Auth
/*
ALTER TABLE public.video_download_jobs
ADD CONSTRAINT video_download_jobs_user_id_foreign
FOREIGN KEY (user_id)
REFERENCES auth.users(id)
ON DELETE SET NULL;
*/
