<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations for Supabase PostgreSQL.
     */
    public function up(): void
    {
        Schema::create('video_download_jobs', function (Blueprint $table) {
            $table->id(); // BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
            $table->uuid('user_id')->nullable()->index();
            $table->text('source_url');
            $table->string('platform', 30)->nullable();
            $table->string('title', 500)->nullable();
            $table->string('author', 255)->nullable();
            $table->text('thumbnail_url')->nullable();
            $table->string('requested_format', 20)->default('mp4');
            $table->string('requested_quality', 30)->nullable();
            $table->string('format_id', 100)->nullable();
            $table->text('file_path')->nullable();
            $table->string('file_name', 500)->nullable();
            $table->bigInteger('file_size')->nullable();
            $table->integer('duration')->nullable();
            $table->smallInteger('progress')->default(0);
            $table->string('status', 30)->default('pending')->index();
            $table->text('error_message')->nullable();
            $table->timestampTz('expires_at')->nullable()->index();
            $table->timestampsTz();

            $table->index(['user_id', 'status']);
        });

        // PostgreSQL Check Constraints
        DB::statement("
            ALTER TABLE public.video_download_jobs 
            ADD CONSTRAINT video_download_jobs_progress_check 
            CHECK (progress >= 0 AND progress <= 100)
        ");

        DB::statement("
            ALTER TABLE public.video_download_jobs 
            ADD CONSTRAINT video_download_jobs_status_check 
            CHECK (status IN ('pending', 'inspecting', 'ready', 'processing', 'completed', 'failed', 'expired'))
        ");

        DB::statement("
            ALTER TABLE public.video_download_jobs 
            ADD CONSTRAINT video_download_jobs_format_check 
            CHECK (requested_format IN ('mp4', 'mp3'))
        ");

        // Optional: Tự động gắn Foreign Key nếu ứng dụng sử dụng auth.users của Supabase Auth
        /*
        DB::statement("
            ALTER TABLE public.video_download_jobs
            ADD CONSTRAINT video_download_jobs_user_id_foreign
            FOREIGN KEY (user_id)
            REFERENCES auth.users(id)
            ON DELETE SET NULL;
        ");
        */

        // Optional: Nếu ứng dụng dùng public.app_users (như ứng dụng Node.js hiện tại)
        /*
        DB::statement("
            ALTER TABLE public.video_download_jobs
            ADD CONSTRAINT video_download_jobs_app_user_id_foreign
            FOREIGN KEY (user_id)
            REFERENCES public.app_users(id)
            ON DELETE SET NULL;
        ");
        */
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('video_download_jobs');
    }
};
